/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ArrayQueue;

public class Library {
    public static void main (String[] args) {
    	ArrayQueue queue = new ArrayQueue(5);
    	try {
	    	queue.enqueue(1);
	    	queue.enqueue(2);
	    	queue.enqueue(3);
	    	queue.enqueue(4);
	    	queue.enqueue(5);
	    	queue.enqueue(6);

    	}catch (Exception e) {
			System.out.println(e.getMessage());
		}
    	try {
	    	System.out.println(queue.dequeue());
	    	System.out.println(queue.dequeue());
	    	System.out.println(queue.dequeue());
	    	System.out.println(queue.dequeue());
	    	System.out.println(queue.dequeue());
	    	System.out.println(queue.dequeue());
    	}catch (Exception e) {
			System.out.println(e.getMessage());
		}
    	
    	try {
    		queue.enqueue(10);
    		queue.enqueue(20);
    		queue.enqueue(30);
    		System.out.println("expecting: 10 actual is: " + queue.dequeue());
    		System.out.println("expecting: 20 actual is: " + queue.dequeue());
    		queue.enqueue(40);
    		queue.enqueue(50);
    		queue.enqueue(60);
    		queue.enqueue(70);
    		queue.enqueue(90);
    		
    	}catch (Exception e) {
			System.out.println(e.getMessage());
		}
    	
    	try {
    		System.out.println("expecting: 30 actual is: " + queue.dequeue());
    		System.out.println("expecting: 40 actual is: " + queue.dequeue());
    		System.out.println("expecting: 50 actual is: " + queue.dequeue());
    		System.out.println("expecting: 60 actual is: " + queue.dequeue());
    		queue.enqueue(80);
    		System.out.println("expecting: 70 actual is: " + queue.dequeue());
    		System.out.println("expecting: 80 actual is: " + queue.dequeue());
    		System.out.println(queue.dequeue());
    	}catch (Exception e) {
			System.out.println(e.getMessage());
		}    	
    }
}
