/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedLists;

public class LLReverse {
    public static LinkedList reverse(LinkedList root) {
        LinkedList curr = root;
        LinkedList prev = null;
        LinkedList temp = null;
        
        while(curr.next != null) {
        	temp = curr.next;
        	curr.next = prev;
        	prev = curr;
        	curr = temp;
        }
        
        curr.next = prev;
            	
    	return curr;
    }
    
    public static void main (String[] args) {
    	LinkedList list = new LinkedList(1);
    	list.addToList(new LinkedList(2));
    	list.addToList(new LinkedList(3));
    	list.addToList(new LinkedList(4));
    	
    	System.out.println("The list is:");
    	list.printList();
    	LinkedList result = reverse(list);
    	System.out.println("result is");
    	result.printList();
    }
}
